CREATE TABLE XXAK_COMMON_ERROR_LOG_T
(
  PROGRAM_NAME      VARCHAR2(100 BYTE),
  REQUEST_ID        VARCHAR2(10 BYTE),
  RECORD_SR_NO      NUMBER,
  BATCH_ID          NUMBER,
  KEY_COLUMN_NAME   VARCHAR2(60 BYTE),
  KEY_COLUMN_VALUE  VARCHAR2(2000 BYTE),
  COLUMN_NAME       VARCHAR2(60 BYTE),
  COLUMN_VALUE      VARCHAR2(2000 BYTE),
  ERROR_MESSAGE     VARCHAR2(3000 BYTE)
) ;

/
SHOW ERRORS;
EXIT;